name: Auto Daily LPR Training

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  train:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r ../gpu-synthetic-pipeline/requirements.txt
    
    - name: Configure Git
      run: |
        git config --global user.email "ci@github.com"
        git config --global user.name "GitHub Actions"
    
    - name: Run auto training pipeline
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd auto-training-pipeline
        python trainer.py
    
    - name: Upload results to artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: training-results
        path: |
          auto-training-pipeline/runs/
          auto-training-pipeline/logs/
        retention-days: 30
    
    - name: Push weights to HuggingFace
      if: success()
      run: |
        pip install huggingface-hub
        python -c "
        from huggingface_hub import HfApi
        import os
        api = HfApi()
        best_model = 'auto-training-pipeline/runs/detect/vn-lpr-*/weights/best.pt'
        if os.path.exists(best_model):
            api.upload_file(
                path_or_fileobj=best_model,
                path_in_repo='best.pt',
                repo_id='vietnamese-lpr-models',
                repo_type='model'
            )
        "
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
    
    - name: Notify status
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Auto LPR Training Pipeline - ${{ job.status }}'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      continue-on-error: true
